### ISSUE TITLE
Mvp created in a wrong module

### ISSUE THREAD

**Issue by mancj** [gmatyszczak/screen-generator-plugin#1] opened 2019-03-07 08:59 UTC
Hi, thank you for the great plugin!
In my project i have 3 modules for clean architecture (data, domain, presentation).
When i select some package in the presentation module and create files with your plugin, they are created in a wrong module (domain).

**Comment by gmatyszczak** [comment] 2019-03-07 09:06
Hi, thanks for trying it out!
For now plugin supports only single module projects (it will create files in the first module that it will find). But I'm working on adding functionality to choose module that you want to add your files to, so stay tuned!

**Comment by gmatyszczak** [comment] 2019-03-07 16:57
@mancj You can update the plugin to version 1.0.0 already. Now you can choose in which module you want to create the files

**Comment by mancj** [comment] 2019-03-12 10:12
I updated the plugin to 1.0.0. But now i get this error when do New->Screen 
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at data.repository.SourceRootRepositoryImpl.findCodeSourceRoot(SourceRootRepository.kt:29)
	at data.file.PackageExtractorImpl.extractFromCurrentPath(PackageExtractor.kt:14)
	at ui.newscreen.NewScreenPresenter.onLoadView(NewScreenPresenter.kt:18)
	at ui.newscreen.NewScreenDialog.createCenterPanel(NewScreenDialog.kt:37)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1302)
	at ui.newscreen.NewScreenDialog.<init>(NewScreenDialog.kt:26)
	at ui.newscreen.NewScreenAction.actionPerformed(NewScreenAction.kt:16)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:255)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:294)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:529)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:49)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:549)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gmatyszczak** [comment] 2019-03-13 07:34
Confirmed, there seems to be a problem when you have selected a file in your project explorer that is not in any module but in the main project folder and try to create a new screen. Is that your case?

**Comment by mancj** [comment] 2019-03-13 15:36
Here is the case:
It is working when i select any file in **data** and **domain** modules. Also it is working on when i select module folders.
But it isn't working outside of them, even on the **presentation** module folder or files.

**Comment by gmatyszczak** [comment] 2019-03-25 15:45
@mancj Please check version 1.0.1, it should be fixed now :)

**Closed by gmatyszczak** 2019-03-25 15:45 UTC
Labels: enhancement

**Comment by mancj** [comment] 2019-03-25 16:07
Thank you! I will check it.
